baseURL = 'https://ejedavy.github.io/queue-management-docs/'
languageCode = 'en-us'
title = 'Queue Management System Developer Docuementation'

# Change the default theme
theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]